# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/shuriken-db/src/db/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
with_docs = true
patch_file = "crates/shuriken-db/src/db/schema.patch"

[migrations_directory]
dir = "crates/shuriken-db/migrations"
