services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: shuriken
      POSTGRES_PASSWORD: shuriken
      POSTGRES_DB: shuriken
    ports:
      - "4523:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  postgres_test:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: shuriken
      POSTGRES_PASSWORD: shuriken
      POSTGRES_DB: shuriken_test
    ports:
      - "4524:5432"

volumes:
  pgdata:
