# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/component/db/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
with_docs = true
patch_file = "src/db/schema.patch"

[migrations_directory]
dir = "migrations"
